export default {
  initial: "Initial",
  login: "Login",
  register: "Register",
  home: "Home",
  calendar: "Calendar",
  training: "Training",
  diary: "Diary",
  pet: "Pet",
  profile: "Profile",
  vetAppointments: "VetAppointments",
  body: "Body",
  medication: "Medication",
  feeding: "Feeding",
  addPet: "AddPet",
  scheduleMed: "ScheduleMedication",
  scheduleFed: "ScheduleFeeding",
  scheduleGroom: "ScheduleGrooming",
  newTraining: "NewTraining",
  pickPet: "Pick Pet"
};
